### ISSUE TITLE
Yearly TOTD ranking

### ISSUE THREAD

**Issue by DocterurGui** [davidbmaier/totd-bot#4]
Could you please add a '!totd ranking last year' to the ranking already available of this month, last month and all time ? Maybe a custom date could be cool to, like '!totd ranking DD-MM-YYYY' ?

**Comment by davidbmaier** [comment]
Custom date is probably not gonna happen since I'd have to store all ratings for all maps - I'd like to keep the bot's persistence footprint as small as possible.
But a "last year" and "current year" category should be easily doable - will take a look once I have some time.

**Comment by davidbmaier** [comment]
Added them in https://github.com/davidbmaier/totd-bot/commit/ccef5fddb14864ac998d84b34edbc0bae6dea00f - I'll add the commands to the help info soon.

**Comment by davidbmaier** [comment]
Implemented and documented 👍
