### ISSUE TITLE
Use new formatting for command names in /help

### ISSUE THREAD

**Issue by nbeerten** [davidbmaier/totd-bot#6]
Discord allows for clickable commands anywhere since a while. This would be useful for the /help overview of commands and allows users to click on the command they want to use.
The format is: `</{commandname}:{commandid}>`. For e.g. the /today command it would look like: `</today:962662886038208512>`. And in discord it'll look like:
![Example](https://user-images.githubusercontent.com/59444993/190485641-9eca13a8-2220-4820-b62d-9a27da941760.png)

**Comment by davidbmaier** [comment]
Cool idea, wasn't aware of that.
Getting the command IDs is a little annoying, but I think I found an alright solution - it's live already, feel free to test it out.
Added in https://github.com/davidbmaier/totd-bot/commit/119d6b261e82034d7d63207d3a0791e762e66998.
